server:
  port: 8092

spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:shop}
      username: ${DB_USER:root}
      password: ${DB_PWD:root}
